version: "3.3"
services:
  command:
    image: bhuwanupadhyay/employees-command
    build:
      context: employees-command
    ports:
      - 8080
  query:
    image: bhuwanupadhyay/employees-query
    build:
      context: employees-query
    ports:
      - 8080
  ui:
    image: bhuwanupadhyay/employees-ui
    build:
      context: employees-ui
    ports:
      - 80