version: '3.7'
services:
  primary:
    image: bitnami/postgresql:12
    ports:
      - 5432
    volumes:
      - postgres-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=employees
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
  replica:
    image: bitnami/postgresql:12
    ports:
      - 5432
    depends_on:
      - primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=primary
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  command:
    image: bhuwanupadhyay/employees-command
    ports:
      - 8080
    depends_on:
      - primary
    environment:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.liquibase.enabled=true
      - spring.datasource.username=repl_user
      - spring.datasource.password=repl_password
      - spring.datasource.url=jdbc:postgresql://primary:5432/employees
      - logging.level.liquibase=INFO
    networks:
      - backend
  query:
    image: bhuwanupadhyay/employees-query
    ports:
      - 8080
    depends_on:
      - replica
    environment:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.liquibase.enabled=true
      - spring.datasource.username=repl_user
      - spring.datasource.password=repl_password
      - spring.datasource.url=jdbc:postgresql://replica:5432/employees
      - logging.level.liquibase=INFO
    networks:
      - backend
  ui:
    image: bhuwanupadhyay/employees-ui
    ports:
      - 80
    networks:
      - frontend

volumes:
  postgres-data:

networks:
  backend:
  frontend: